there is an exception Traceback (most recent call last):
  File "<ipython-input-15-27658e938384>", line 6, in <module>
    raise Exception("this is error message")
Exception: this is error message
there is an exception Traceback (most recent call last):
  File "<ipython-input-18-6df447489be7>", line 6, in <module>
    raise Exception("this is error message")
Exception: this is error message
there is an exception Traceback (most recent call last):
  File "<ipython-input-19-96c8ee418f4b>", line 6, in <module>
    raise Exception("this is error message")
Exception: this is error message
there is an exception Traceback (most recent call last):
  File "<ipython-input-7-96c8ee418f4b>", line 6, in <module>
    raise Exception("this is error message")
Exception: this is error message
there is an exception Traceback (most recent call last):
  File "<ipython-input-12-96c8ee418f4b>", line 6, in <module>
    raise Exception("this is error message")
Exception: this is error message
